### ISSUE TITLE
Not using `OptKillOldDelay` and `OptEnableAutoRestart` option?

### ISSUE THREAD

**Issue by sioncojp** [lestrrat-go/server-starter#15]
https://github.com/lestrrat/go-server-starter/blob/master/starter.go#L439..L448

I see that `OptKillOldDelay` and `OptEnableAutoRestart` doesn't use because there has used `Environment variable`.

What there should be use option value?

**Comment by lestrrat** [comment]
sorry, that makes no sense: 

> I see that OptKillOldDelay and OptEnableAutoRestart doesn't use because there has used Environment variable.

日本語でどうぞー

**Comment by sioncojp** [comment]
すみません。

`--kill-old-delay=seconds`オプションが使われてない（その代わり環境変数でoverwrite）ように見受けられたので、不要ではないかと思いました。

`--enable-auto-restart`オプションはUNIMPLEMENTEDと書かれてましたので解決しました。失念しており、申し訳ないです。

**Comment by lestrrat** [comment]
そのあたりは #11 でやった気がします。ただし、テストが進んで無くてマージしてない感じです。
もし確認してもらえるなら最高です！

**Comment by sioncojp** [comment]
ご回答ありがとうございます！
時間あるときに一度確認してみます〜。
