### ISSUE TITLE
Add: a method which hook after graceful shutdown.

### ISSUE THREAD

**Issue by sioncojp** [lestrrat-go/server-starter#16]
https://github.com/lestrrat/go-server-starter/blob/master/starter.go#L429

I wanna hook after graceful shutdown.

The line of target in which graceful restart logic is called `syscall.SIGTERM`.
（Unfortunately, the line is naming s.signalOnHUP.
    That identification's PR is https://github.com/lestrrat/go-server-starter/pull/14 ）

I've hooked to receive a channel calling `syscall.SIGTERM`, 
```go
// create a hook point to receive a channel in my main.go
case syscall.SIGTERM:
  want execute logic after shutdown....
```
but it has executed both graceful restart and shutdown.

Because [L429](https://github.com/lestrrat/go-server-starter/pull/14/files#diff-f1a9e20d69bdf36a51fdc23929c51b10L429) calls `SIGTERM` to kill process in `graceful restart` logic.
And so a hook point wrong recieved `SIGTERM`.

What do you think about that it should be a method which hook after graceful shutdown?

**Comment by lestrrat** [comment]
> Because L429 calls SIGTERM to kill process in graceful restart logic.

Use `start_server --signal-on-hup=XXX` to change the signal that gets sent when HUP is sent to start_server

**Comment by sioncojp** [comment]
I got it. Thank you!!!
Close this PR.
